### ISSUE TITLE
Extract website icon

### ISSUE THREAD

**Issue by vivekatro** [jacktuck/unfurl#28]
First of all, awesome work!
It would be great we you can extract the site icon in the response as well :)

**Comment by jacktuck** [comment]
@vivekatro Thanks for the kind words.

I think I'd like to keep the library as simple as possible and just return all possible metadata which would let you search for the icon yourself. Rather than handling the many varying cases someone might want to scrape a website.

That said if anything is missing and blocking you from fetching the icon that's something i'd definitely take a look at fixing.

Please re-open if you find any missing metadata that blocks you. Thanks again :)
